/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kontaktlisa;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author pavpa01
 */

/**
 * JFrame-klass som hanterar användargränssnittet för kontaktlistan.
 * Härifrån kan användaren se, lägga till och radera kontakter.
 */
public class KontaktlistaJFrame extends javax.swing.JFrame {

    DBManager db = new DBManager();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KontaktlistaJFrame.class.getName());
    // private String Telefonummer;

    /**
     * Creates new form kontaktlista
     */
    
    // Initierar alla GUI-komponenter (knappar, fält etc.)
// Kollar vilket sorteringsval som är förvalt och fyller listan direkt vid start
    public KontaktlistaJFrame() {
        initComponents();
        if (this.rbtnförnamnFörst.isSelected()) {
            skrivUtFörnamn();
        } else {
            skrivUtEfternamn();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tbxFörnamn = new javax.swing.JTextField();
        rbtnförnamnFörst = new javax.swing.JRadioButton();
        rbtnefternamnFörst = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tbxEfternamn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tbxTelefonummer = new javax.swing.JTextField();
        BtnLäggtill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaLista = new javax.swing.JTextArea();
        btnraderaKontakt = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Förnamn");

        buttonGroup1.add(rbtnförnamnFörst);
        rbtnförnamnFörst.setSelected(true);
        rbtnförnamnFörst.setText("Förnamn först");
        rbtnförnamnFörst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnförnamnFörstActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnefternamnFörst);
        rbtnefternamnFörst.setText("Efternamn först");
        rbtnefternamnFörst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnefternamnFörstActionPerformed(evt);
            }
        });

        jLabel2.setText("Efternamn");

        jLabel3.setText("Telefonummer");

        BtnLäggtill.setText("Lägg till");
        BtnLäggtill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLäggtillActionPerformed(evt);
            }
        });

        txaLista.setColumns(20);
        txaLista.setRows(5);
        jScrollPane1.setViewportView(txaLista);

        btnraderaKontakt.setText("Radera Kontakt");
        btnraderaKontakt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraderaKontaktActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbxEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnförnamnFörst)
                        .addGap(83, 83, 83)
                        .addComponent(rbtnefternamnFörst)
                        .addContainerGap(104, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tbxTelefonummer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(BtnLäggtill)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnraderaKontakt)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tbxFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tbxTelefonummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLäggtill))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnraderaKontakt)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnförnamnFörst)
                    .addComponent(rbtnefternamnFörst))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnförnamnFörstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnförnamnFörstActionPerformed
        skrivUtFörnamn();

    }//GEN-LAST:event_rbtnförnamnFörstActionPerformed
/**
     * Körs när användaren väljer "efternamn först" i radioknapparna.
     */
    private void rbtnefternamnFörstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnefternamnFörstActionPerformed
        this.txaLista.setText("");

        skrivUtEfternamn();

                                                 }//GEN-LAST:event_rbtnefternamnFörstActionPerformed

/**
     * Hanterar logiken för att lägga till en ny kontakt i databasen.
     */
    // 1. Hämta text från inmatningsfälten
    // 2. Töm fälten så de är redo för nästa inmatning
    // 3. Validera att inga fält är tomma innan vi skickar till databasen
    // 4. Uppdatera listan i fönstret så den nya kontakten syns direkt
    private void BtnLäggtillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLäggtillActionPerformed
        String Förnamn = this.tbxFörnamn.getText();
        this.tbxFörnamn.setText("");
        String Efternamn = this.tbxEfternamn.getText();
        this.tbxEfternamn.setText("");
        String Telefonnummer = this.tbxTelefonummer.getText();
        this.tbxTelefonummer.setText("");

        System.out.println(Telefonnummer);
        if (!Förnamn.isBlank() && !Efternamn.isBlank() && !Telefonnummer.isBlank()) {
            Kontakt kon = new Kontakt(Förnamn, Efternamn, Telefonnummer);
            db.insert(kon);

        }

        if (this.rbtnförnamnFörst.isSelected()) {
            skrivUtFörnamn();
        } else {
            skrivUtEfternamn();

        }


    }//GEN-LAST:event_BtnLäggtillActionPerformed
/**
     * Hanterar logiken för att radera en kontakt baserat på ID.
     */
    // Hämta ID från textfältet och ta bort mellanslag
    // Omvandla text till siffra
    // Sedan anropa DBManager för att utföra raderingen i databasen
    // Uppdatera listan på skärmen
    private void btnraderaKontaktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraderaKontaktActionPerformed
        // TODO add your handling code here:private void btnraderaKontaktActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        try {

            String input = jTextField1.getText().trim();
            if (!input.isEmpty()) {
                int id = Integer.parseInt(input);
                db.delete(id);
                jTextField1.setText("");

                if (this.rbtnförnamnFörst.isSelected()) {
                    skrivUtFörnamn();
                } else {
                    skrivUtEfternamn();
                }
                System.out.println("Kontakt med ID " + id + " raderades.");
            } else {
                System.out.println("Du måste skriva ett ID i rutan!");
            }
        } catch (NumberFormatException e) {
            System.out.println("Fel: Du måste skriva en siffra (ID).");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnraderaKontaktActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KontaktlistaJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLäggtill;
    private javax.swing.JButton btnraderaKontakt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rbtnefternamnFörst;
    private javax.swing.JRadioButton rbtnförnamnFörst;
    private javax.swing.JTextField tbxEfternamn;
    private javax.swing.JTextField tbxFörnamn;
    private javax.swing.JTextField tbxTelefonummer;
    private javax.swing.JTextArea txaLista;
    // End of variables declaration//GEN-END:variables
/**
     * Hämtar all data och skriver ut den med Förnamn först.
     */
    // Rensa rutan först
    // Hämtar kolumner från databasen och lägger till i textrutan
    private void skrivUtFörnamn() {
        this.txaLista.setText("");
        ResultSet rs = db.getAllData();
        if (rs != null) {
            try {
                while (rs.next()) {
                    this.txaLista.append(rs.getInt("kontaktid") + "\t "
                            + rs.getString("firstname") + "\t "
                            + rs.getString("lastname") + "\t "
                            + rs.getString("phonenumber") + "\n ");

                }
            } catch (SQLException ex) {
                System.out.println("Ingen data");
            }
        } else {
            System.out.println("Ingen data från databasen, kontrollera anslutningen.");
        }

    }

   /**
     * Hämtar all data och skriver ut den med Efternamn först.
     */
    // Rensa rutan först
    // Samma som ovan men kastar om ordningen på kolumnerna vid utskrift
    private void skrivUtEfternamn() {
        this.txaLista.setText("");
        this.txaLista.setText("");
        ResultSet rs = db.getAllData();
        if (rs != null) {
            try {
                while (rs.next()) {
                    this.txaLista.append(rs.getInt("kontaktid") + "\t "
                            + rs.getString("lastname") + "\t "
                            + rs.getString("firstname") + "\t "
                            + rs.getString("phonenumber") + "\n ");

                }
            } catch (SQLException ex) {
                System.out.println("Ingen data");
            }
        } else {
            System.out.println("Ingen data från databasen, kontrollera anslutningen.");
        }

    }

}
